# NOTE: update this with your service name
service: cognito-triggers-sls

projectDir: '../'

plugins:
  # - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  # - serverless-dotenv-plugin # Load .env as environment variables

provider:
  iamRoleStatements:
    - Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Effect: Allow
      Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  stage: dev
  versionFunctions: false
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9998
    lambdaPort: 9997

# functions:
#   cognito-triggers:
#     handler: handler.handler
#     events:
#       - http:
#           path: /cognito
#           method: post
#           async: true

# hello:
#   handler: handler.hello
#   events:
#     - http:
#         path: hello
#         method: get
#         async: true

# cognitoTriggers:
#   handler: handler.cognitoTriggers
#   events:
#     - http:
#         path: /cognito
#         method: post
#         async: true

# toBeInvoked:
#   handler: handler.toBeInvoked

functions:
  PostAuthentication_Authentication:
    # events:
    #   - http:
    #       method: post
    #       path: /cognito
    handler: handler.PostAuthentication_Authentication

  # toBeInvoked:
  #   handler: handler.toBeInvoked
