name: E2E Cypress Public

on:
  pull_request:
  push:
    branches:
      - flakey-tests
jobs:
  e2e_cypress_public:
    runs-on: macos-latest
    env:
      CI: true
      CHECK_DEPLOY_DATE_INTERVAL: 5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        run: npm ci
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          npm run cypress:integration:public
