name: E2E Cypress

on:
  pull_request:
  push:
    branches:
      - flakey-tests

jobs:
  e2e_cypress:
    runs-on: macos-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        run: npm ci
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          npm run cypress:integration
      - name: Store Logs
        uses: actions/upload-artifact@v3
        with:
          name: cypress-logs
          path: /tmp/cypress
