name: verify pdfs

on:
  pull_request:
  push:
    branches:
      - dependency-updates

jobs:
  test_pdfs:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/x1k7v5e2/ef-cms-us-east-1-public:b3.0.0
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          mkdir -p .husky/_
      - name: NPM Install
        run: npm ci --legacy-peer-deps && npm rebuild
      - name: Generate PDFs
        run: npm run test:pdf-output
      - name: Compare Images
        run: node image-compare-pdfs.js
