name: Node.js CI - shared

on:
  pull_request:
  push:
    branches:
      - dependency-updates
      - test
      - 9616-story

jobs:
  Shared:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Shared
        run: |
          npm ci --legacy-peer-deps
          npm run test:shared
