name: Node.js CI - Shared

on:
  pull_request:
  push:
    branches:
      - flakey-tests

jobs:
  Shared:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        run: npm ci
      - name: Shared
        run: npm run test:shared
