name: E2E Cypress

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - 'ustc-3866-flaky-cypress-click-cicd'

jobs:
  e2e_cypress:
    runs-on: ubuntu-latest

    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          export CYPRESS_TEMP_DOCUMENTS_BUCKET_NAME=noop-temp-documents-local-us-east-1
          export CYPRESS_QUARANTINE_BUCKET_NAME=noop-quarantine-local-us-east-1
          export CYPRESS_DOCUMENTS_BUCKET_NAME=noop-documents-local-us-east-1
          export CYPRESS_S3_ENDPOINT=http://0.0.0.0:9000
          export CYPRESS_MASTER_DYNAMODB_ENDPOINT=http://localhost:8000
          export CYPRESS_SLS_DEPLOYMENT_BUCKET=noop
          export CYPRESS_AWS_ACCESS_KEY_ID=S3RVER
          export CYPRESS_AWS_SECRET_ACCESS_KEY=S3RVER
          export CYPRESS_CHECK_DEPLOY_DATE_INTERVAL=5000
          ./node_modules/.bin/cypress run --browser "edge" -C "cypress.config.ts" --spec cypress/cypress-integration/integration/start-a-case-practitioner.cy.ts
      - name: Store Cypress Failure Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/cypress-integration/videos
