name: Typescript Untouched File Check

on:
  pull_request:
  push:
    branches:
      - dependency-updates

jobs:
  CheckUntouchedFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout USTC Staging
        uses: actions/checkout@v3
        with:
          repository: ustaxcourt/ef-cms
          ref: staging
          path: stagingBranch
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: NPM Install in your branch
        run: npm ci
      - name: NPM Install in staging
        working-directory: ./stagingBranch
        run: npm ci
      - name: Check untouched files
        run: npx ts-node scripts/checkUntouchedFiles.ts
